FROM jupyter/scipy-notebook 

# copy analysis file 
COPY analysis/Unit5_cdc.ipynb analysis/Unit5_cdc.ipynb

# copy data 
COPY data/1971.csv.gz data/1971.csv.gz

# install any other packages needed 
RUN pip install --no-cache-dir numpy plotly ipython

